"""empty message

Revision ID: ac7ba16aeb79
Revises: 
Create Date: 2020-03-20 20:11:17.889613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7ba16aeb79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints-companies',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('company_response_user', sa.String(), nullable=True),
    sa.Column('company_response_public', sa.String(), nullable=True),
    sa.Column('was_response_timely', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_table('issues',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('main_issue', sa.String(), nullable=True),
    sa.Column('sub_issue', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('main_product', sa.String(), nullable=True),
    sa.Column('sub_product', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('complaints-users',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('complaint_text', sa.Text(), nullable=True),
    sa.Column('was_user_disputed', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaints-users')
    op.drop_table('products')
    op.drop_table('issues')
    op.drop_table('complaints-companies')
    # ### end Alembic commands ###
